<?php

/**
 * @file
 * Plugin definition for the File key provider.
 */

/**
 * The default plugin configuration.
 *
 * @return array
 *   The default plugin configuration.
 */
function key_provider_file_default_configuration() {
  return array(
    'file_location' => '',
    'strip_line_breaks' => FALSE,
    'base64_encoded' => FALSE,
  );
}

/**
 * Build the plugin configuration form.
 *
 * @return array
 *   The plugin configuration form.
 */
function key_provider_file_build_configuration_form($form, &$form_state) {
  $config = $form_state['storage']['key_config'];
  $plugin_config = $form_state['storage']['key_config']['key_provider_settings'] + key_provider_file_default_configuration();
  $is_new = empty($config['id']);

  $form['file_location'] = array(
    '#type' => 'textfield',
    '#title' => t('File location'),
    '#default_value' => $plugin_config['file_location'],
    '#disabled' => TRUE,
    '#access' => !$is_new,
  );

  $form['strip_line_breaks'] = array(
    '#type' => 'checkbox',
    '#title' => t('Strip trailing line breaks'),
    '#description' => t('Check this to remove any trailing line breaks from the file. Leave unchecked if there is a chance that a line break could be a valid character in the key. Only affects retrieving the value and not when saving.'),
    '#default_value' => $plugin_config['strip_line_breaks'],
  );

  // If this is for an encryption key.
  $key_type = key_get_key_type_info($config['key_type']);
  if ($key_type['group'] == 'encryption') {
    // Add an option to indicate that the value is Base64-encoded.
    $form['base64_encoded'] = array(
      '#type' => 'checkbox',
      '#title' => t('Base64-encoded'),
      '#description' => t('Checking this will store the key with Base64 encoding. Can only be set on new keys.'),
      '#default_value' => $plugin_config['base64_encoded'],
      '#disabled' => !$is_new,
    );
  }

  return $form;
}

/**
 * Validate callback for the configuration form.
 */
function key_provider_file_validate_configuration_form($form, &$form_state) {
  // Filename only present if the key config already exists.
  $filename = $form_state['values']['file_location'];

  // Check that private file system is set.
  if (!config_get('system.core', 'file_private_path')) {
    form_error($form, t(
      'The <a href="@filesystem_settings">Private file system path</a> (e.g., %str) needs to be set in order for the private key provider to save this key.',
      array(
        '@filesystem_settings' => url('admin/config/media/file-system'),
        '%str' => 'private://',
      )
    ));
    return;
  }

  if (!$filename) {
    // Test the private://keys directory can be created.
    $directory = _key_create_private_keys_directory();

    if (!$directory) {
      form_error($form, t(
        'The private keys directory does not exist and cannot be created. Ensure that the <a href="@filesystem_settings">Private file system path</a> (e.g., %str) has been set and is writable.',
        array(
          '@filesystem_settings' => url('admin/config/media/file-system'),
          '%str' => 'private://',
        )
      ));
      return;
    }
  }
  else {
    // If a filename is specified, does the file exist?
    if (!is_file($filename)) {
      form_set_error('file_location', t('There is no file at the specified location.'));
      return;
    }

    // Is the file readable?
    if ((!is_readable($filename))) {
      form_set_error('file_location', t('The file at the specified location is not readable.'));
      return;
    }
  }
}

/**
 * Callback function to return a key from a file.
 */
function key_provider_file_get_key_value($config) {
  if (empty($config['key_provider_settings']['file_location'])) {
    return NULL;
  }
  $filename = $config['key_provider_settings']['file_location'];

  // Make sure the file exists and is readable.
  if (!is_file($filename) || !is_readable($filename)) {
    return NULL;
  }

  $key_value = file_get_contents($filename);

  if (isset($config['key_provider_settings']['strip_line_breaks']) && $config['key_provider_settings']['strip_line_breaks']) {
    $key_value = rtrim($key_value, "\n\r");
  }

  // Base64 decode if necessary.
  if (isset($config['key_provider_settings']['base64_encoded']) && $config['key_provider_settings']['base64_encoded']) {
    $key_value = base64_decode($key_value);
  }

  return $key_value;
}

/**
 * Sets the value of a key.
 *
 * @param array $config
 *   The key configuration for which to set the value.
 * @param array $form_state
 *   The form state.
 * @param string $key_value
 *   The key value.
 *
 * @return bool
 *   TRUE if successful, FALSE if unsuccessful.
 */
function key_provider_file_set_key_value($config, &$form_state, $key_value) {
  $id = $form_state['storage']['key_config']['id'] ?? '';

  if (isset($config['key_provider_settings']['base64_encoded']) && $config['key_provider_settings']['base64_encoded'] == TRUE) {
    $key_value = base64_encode($key_value);
  }

  // Ensure value isn't saved to the config.
  unset($form_state['values']['key_value']);

  if (!$key_value) {
    return FALSE;
  }

  $filename = $form_state['values']['file_location'];
  if (!$filename) {
    $filename = _key_create_private_key_file("{$id}_");
  }
  $status = FALSE;
  if ($filename) {
    $form_state['values']['file_location'] = $filename;
    $status = (bool) file_put_contents($filename, $key_value);
  }

  return $status;
}

/**
 * Modify the delete confirmation form.
 */
function key_provider_file_build_delete_form($form, &$form_state, $config, &$message, &$caption) {
  $caption = '<p>' . t('This action cannot be undone. Any referenced key files will also be deleted. Make backups of any files you wish to keep.') . '</p>';
}

/**
 * Deletes the value of a key.
 *
 * @param array $config
 *   The key configuration whose value will be deleted.
 *
 * @return bool
 *   TRUE if successful, FALSE if unsuccessful.
 */
function key_provider_file_delete_key_value($config) {
  $status = FALSE;
  $filename = $config['key_provider_settings']['file_location'] ?? '';
  $status = $filename ? backdrop_unlink($filename) : FALSE;

  if ($status) {
    backdrop_set_message(t('The deleted key referenced a pre-existing key file, which was also deleted.'));
  }
  return $status;
}
