<?php

/**
 * @file
 * Plugin definition for the generic Encryption key type.
 */

/**
 * The default plugin configuration.
 *
 * @return array
 *   The default plugin configuration.
 */
function key_type_encryption_default_configuration() {
  return array(
    'key_size' => '256',
  );
}

/**
 * Build the plugin configuration form.
 *
 * @return array
 *   The plugin configuration form.
 */
function key_type_encryption_build_configuration_form($form, &$form_state) {
  $config = $form_state['storage']['key_config'];
  $plugin_config = $config['key_type_settings'] + key_type_encryption_default_configuration();

  // Define the most common key size options.
  $key_size_options = array(
    '128' => 128,
    '256' => 256,
  );

  $key_size = $plugin_config['key_size'];
  $key_size_other_value = '';
  if (!in_array($key_size, $key_size_options)) {
    $key_size_other_value = $key_size;
    $key_size = 'other';
  }

  $form['key_size'] = array(
    '#type' => 'select',
    '#title' => t('Key size'),
    '#description' => t('Used to validate the size of the key value. The size of the key in bits, with 8 bits per byte. For example, a string like "12345678901234567890123456789012" has 32 characters/bytes or 256 bits.'),
    '#options' => $key_size_options + array('other' => t('Other')),
    '#default_value' => $key_size,
    '#required' => TRUE,
  );
  $form['key_size_other_value'] = array(
    '#type' => 'number',
    '#title' => t('Key size (other value)'),
    '#title_display' => 'invisible',
    '#description' => t('Enter a custom key size in bits.'),
    '#default_value' => $key_size_other_value,
    '#min' => 1,
    '#max' => 9999,
    '#maxlength'=> 20,
    '#size'=> 20,
    '#states' => array(
      'visible' => array(
        'select[name="key_type_settings[key_size]"]' => array('value' => 'other'),
      ),
      'required' => array(
        'select[name="key_type_settings[key_size]"]' => array('value' => 'other'),
      ),
    ),
  );

  return $form;
}

/**
 * Validate the plugin configuration form.
 */
function key_type_encryption_validate_configuration_form($form, &$form_state) {
  // If 'Other' was selected for the key size, use the custom entered value.
  if ($form_state['values']['key_size'] == 'other') {
    $form_state['values']['key_size'] = $form_state['values']['key_size_other_value'];

    if (!$form_state['values']['key_size']) {
      form_set_error('key_size_other', t('The custom key size cannot be empty.'));
      return;
    }

    if ($form_state['values']['key_size'] && $form_state['values']['key_size'] % 8 > 0) {
      form_set_error('key_size_other', t('The custom key size should divide evenly into 8.'));
      return;
    }
  }
  unset($form_state['values']['key_size_other_value']);
}

/**
 * Generate a key value.
 *
 * @param array $config
 *   The key configuration.
 *
 * @return string
 *   A random key.
 */
function key_type_encryption_generate_key_value($config) {
  $random_key = '';

  if (isset($config['key_type_settings']['key_size'])) {
    $key_size = $config['key_type_settings']['key_size'];
    // If 'Other' was selected for the key size, use the custom entered value.
    if ($key_size == 'other') {
      $key_size = $config['key_type_settings']['key_size_other_value'];
    }
    $bytes = $key_size > 1 ? $key_size / 8 : 0;
  }
  else {
    // If no key size has been defined, use 32 bytes as the default.
    $bytes = 32;
  }

  // If bytes is a round number then generate the key.
  if ($bytes > 1 && $bytes % 1 === 0) {
    $random_key = backdrop_random_bytes($bytes);
  }

  return $random_key;
}

/**
 * Validate the key value.
 *
 * @param string $key_value
 *   The key value to validate.
 */
function key_type_encryption_validate_key_value($form, &$form_state, $key_value) {
  if (empty($form_state['values']['key_size'])) {
    return;
  }

  $is_new = empty($form_state['storage']['original_key']['id']);

  if (!$key_value) {
    if ($is_new) {
      $message = t('Unable to generate a key value.');
    }
    else {
      $message = t('The key value is missing.');
    }
    form_error($form, $message);
    return;
  }

  // Validate the key size.
  $bytes = $form_state['values']['key_size'] / 8;
  if (strlen($key_value) != $bytes) {
    form_set_error('key_size', t('The selected key size does not match the actual size of the key.'));
    return;
  }
}
